/*
 * generated by Xtext
 */
package com.eu.evidence.rtdruid.oil.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class OilExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return com.eu.evidence.rtdruid.oil.xtext.ui.internal.OilActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return com.eu.evidence.rtdruid.oil.xtext.ui.internal.OilActivator.getInstance().getInjector("com.eu.evidence.rtdruid.oil.xtext.Oil");
	}
	
}
