/*
 * generated by Xtext
 */
package com.eu.evidence.rtdruid.oil.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.eu.evidence.rtdruid.oil.xtext.ui.internal.OilActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class OilExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return OilActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return OilActivator.getInstance().getInjector(OilActivator.COM_EU_EVIDENCE_RTDRUID_OIL_XTEXT_OIL);
	}
	
}
