<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="oil" nsURI="http://com.eu.evidence.rtdruid.oil.xtext.model"
    nsPrefix="com.eu.evidence.rtdruid.oil.xtext">
  <eClassifiers xsi:type="ecore:EClass" name="OilObject" eSuperTypes="#//ParameterRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ObjectType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Type" eType="#//ParameterType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="auto" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ValueRef" eType="#//ParameterRef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ObjectType">
    <eLiterals name="OS"/>
    <eLiterals name="ALARM" value="1"/>
    <eLiterals name="APPMODE" value="2"/>
    <eLiterals name="COUNTER" value="3"/>
    <eLiterals name="COM" value="4"/>
    <eLiterals name="EVENT" value="5"/>
    <eLiterals name="IPDU" value="11"/>
    <eLiterals name="ISR" value="8"/>
    <eLiterals name="MESSAGE" value="9"/>
    <eLiterals name="NETWORKMESSAGE" value="10"/>
    <eLiterals name="NM" value="12"/>
    <eLiterals name="RESOURCE" value="7"/>
    <eLiterals name="TASK" value="6"/>
    <eLiterals name="APPLICATION" value="13"/>
    <eLiterals name="SPINLOCK" value="14"/>
    <eLiterals name="SCHEDULETABLE" value="15"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OilApplication">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="OilObjects" upperBound="-1"
        eType="#//OilObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OilImplementation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="OilObjects" upperBound="-1"
        eType="#//OilObjectImpl" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OilObjectImpl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Parameters" upperBound="-1"
        eType="#//ParameterType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ObjectType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterType" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="withAuto" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultAuto" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueType" eSuperTypes="#//ParameterType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//VType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ValidValues" eType="#//ValidValues"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumeratorType" eSuperTypes="#//ParameterRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Parameters" upperBound="-1"
        eType="#//ParameterType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariantType" eSuperTypes="#//ParameterType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//EType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Values" upperBound="-1"
        eType="#//EnumeratorType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VType">
    <eLiterals name="STRING" literal="STRING"/>
    <eLiterals name="UINT32" value="1" literal="UINT32"/>
    <eLiterals name="INT32" value="2" literal="INT32"/>
    <eLiterals name="UINT64" value="5" literal="UINT64"/>
    <eLiterals name="INT64" value="6" literal="INT64"/>
    <eLiterals name="FLOAT" value="3" literal="FLOAT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EType">
    <eLiterals name="BOOLEAN"/>
    <eLiterals name="ENUM" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OilFile">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Implementation" eType="#//OilImplementation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Application" eType="#//OilApplication"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oilVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceType" eSuperTypes="#//ParameterType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ObjectType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterRef" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="PType">
    <eLiterals name="Undefined" value="1"/>
    <eLiterals name="Value"/>
    <eLiterals name="Reference" value="2"/>
    <eLiterals name="Variant" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValidValues" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Range" eSuperTypes="#//ValidValues">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueList" eSuperTypes="#//ValidValues">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
