/*
 * generated by Xtext
 */
package com.eu.evidence.rtdruid.oil.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.documentation.IEObjectDocumentationProvider;
import org.eclipse.xtext.ui.editor.autoedit.AbstractEditStrategyProvider;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;

import com.eu.evidence.rtdruid.oil.xtext.ui.contentassist.OilEditStrategyProvider;
import com.eu.evidence.rtdruid.oil.xtext.ui.hover.OilEObjectDocumentationProvider;
import com.eu.evidence.rtdruid.oil.xtext.ui.hover.OilEObjectHoverProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class OilUiModule extends com.eu.evidence.rtdruid.oil.xtext.ui.AbstractOilUiModule {
	public OilUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider() {
		return OilEObjectHoverProvider.class;
	}

	public Class<? extends IEObjectDocumentationProvider> bindIEObjectDocumentationProviderr() {
		return OilEObjectDocumentationProvider.class;
	}
	
	public Class<? extends AbstractEditStrategyProvider> bindAbstractEditStrategyProvider() {
		return OilEditStrategyProvider.class;
	}

}
