/*
 * generated by Xtext
 */
package com.eu.evidence.rtdruid.oil.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class OilUiModule extends com.eu.evidence.rtdruid.oil.xtext.ui.AbstractOilUiModule {
	public OilUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
